# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /tmp/SVie2520

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /tmp/SVie2520

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /tmp/SVie2520/CMakeFiles /tmp/SVie2520/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /tmp/SVie2520/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named debug

# Build rule for target.
debug: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 debug
.PHONY : debug

# fast build rule for target.
debug/fast:
	$(MAKE) -f CMakeFiles/debug.dir/build.make CMakeFiles/debug.dir/build
.PHONY : debug/fast

#=============================================================================
# Target rules for targets named distclean

# Build rule for target.
distclean: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 distclean
.PHONY : distclean

# fast build rule for target.
distclean/fast:
	$(MAKE) -f CMakeFiles/distclean.dir/build.make CMakeFiles/distclean.dir/build
.PHONY : distclean/fast

#=============================================================================
# Target rules for targets named id_sviewer

# Build rule for target.
id_sviewer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 id_sviewer
.PHONY : id_sviewer

# fast build rule for target.
id_sviewer/fast:
	$(MAKE) -f CMakeFiles/id_sviewer.dir/build.make CMakeFiles/id_sviewer.dir/build
.PHONY : id_sviewer/fast

#=============================================================================
# Target rules for targets named rebuild

# Build rule for target.
rebuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rebuild
.PHONY : rebuild

# fast build rule for target.
rebuild/fast:
	$(MAKE) -f CMakeFiles/rebuild.dir/build.make CMakeFiles/rebuild.dir/build
.PHONY : rebuild/fast

#=============================================================================
# Target rules for targets named release

# Build rule for target.
release: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 release
.PHONY : release

# fast build rule for target.
release/fast:
	$(MAKE) -f CMakeFiles/release.dir/build.make CMakeFiles/release.dir/build
.PHONY : release/fast

src/FBXloader.o: src/FBXloader.cpp.o
.PHONY : src/FBXloader.o

# target to build an object file
src/FBXloader.cpp.o:
	$(MAKE) -f CMakeFiles/id_sviewer.dir/build.make CMakeFiles/id_sviewer.dir/src/FBXloader.cpp.o
.PHONY : src/FBXloader.cpp.o

src/FBXloader.i: src/FBXloader.cpp.i
.PHONY : src/FBXloader.i

# target to preprocess a source file
src/FBXloader.cpp.i:
	$(MAKE) -f CMakeFiles/id_sviewer.dir/build.make CMakeFiles/id_sviewer.dir/src/FBXloader.cpp.i
.PHONY : src/FBXloader.cpp.i

src/FBXloader.s: src/FBXloader.cpp.s
.PHONY : src/FBXloader.s

# target to generate assembly for a file
src/FBXloader.cpp.s:
	$(MAKE) -f CMakeFiles/id_sviewer.dir/build.make CMakeFiles/id_sviewer.dir/src/FBXloader.cpp.s
.PHONY : src/FBXloader.cpp.s

src/func_event.o: src/func_event.cpp.o
.PHONY : src/func_event.o

# target to build an object file
src/func_event.cpp.o:
	$(MAKE) -f CMakeFiles/id_sviewer.dir/build.make CMakeFiles/id_sviewer.dir/src/func_event.cpp.o
.PHONY : src/func_event.cpp.o

src/func_event.i: src/func_event.cpp.i
.PHONY : src/func_event.i

# target to preprocess a source file
src/func_event.cpp.i:
	$(MAKE) -f CMakeFiles/id_sviewer.dir/build.make CMakeFiles/id_sviewer.dir/src/func_event.cpp.i
.PHONY : src/func_event.cpp.i

src/func_event.s: src/func_event.cpp.s
.PHONY : src/func_event.s

# target to generate assembly for a file
src/func_event.cpp.s:
	$(MAKE) -f CMakeFiles/id_sviewer.dir/build.make CMakeFiles/id_sviewer.dir/src/func_event.cpp.s
.PHONY : src/func_event.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/id_sviewer.dir/build.make CMakeFiles/id_sviewer.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/id_sviewer.dir/build.make CMakeFiles/id_sviewer.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/id_sviewer.dir/build.make CMakeFiles/id_sviewer.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/matrix.o: src/matrix.cpp.o
.PHONY : src/matrix.o

# target to build an object file
src/matrix.cpp.o:
	$(MAKE) -f CMakeFiles/id_sviewer.dir/build.make CMakeFiles/id_sviewer.dir/src/matrix.cpp.o
.PHONY : src/matrix.cpp.o

src/matrix.i: src/matrix.cpp.i
.PHONY : src/matrix.i

# target to preprocess a source file
src/matrix.cpp.i:
	$(MAKE) -f CMakeFiles/id_sviewer.dir/build.make CMakeFiles/id_sviewer.dir/src/matrix.cpp.i
.PHONY : src/matrix.cpp.i

src/matrix.s: src/matrix.cpp.s
.PHONY : src/matrix.s

# target to generate assembly for a file
src/matrix.cpp.s:
	$(MAKE) -f CMakeFiles/id_sviewer.dir/build.make CMakeFiles/id_sviewer.dir/src/matrix.cpp.s
.PHONY : src/matrix.cpp.s

src/mesh.o: src/mesh.cpp.o
.PHONY : src/mesh.o

# target to build an object file
src/mesh.cpp.o:
	$(MAKE) -f CMakeFiles/id_sviewer.dir/build.make CMakeFiles/id_sviewer.dir/src/mesh.cpp.o
.PHONY : src/mesh.cpp.o

src/mesh.i: src/mesh.cpp.i
.PHONY : src/mesh.i

# target to preprocess a source file
src/mesh.cpp.i:
	$(MAKE) -f CMakeFiles/id_sviewer.dir/build.make CMakeFiles/id_sviewer.dir/src/mesh.cpp.i
.PHONY : src/mesh.cpp.i

src/mesh.s: src/mesh.cpp.s
.PHONY : src/mesh.s

# target to generate assembly for a file
src/mesh.cpp.s:
	$(MAKE) -f CMakeFiles/id_sviewer.dir/build.make CMakeFiles/id_sviewer.dir/src/mesh.cpp.s
.PHONY : src/mesh.cpp.s

src/node.o: src/node.cpp.o
.PHONY : src/node.o

# target to build an object file
src/node.cpp.o:
	$(MAKE) -f CMakeFiles/id_sviewer.dir/build.make CMakeFiles/id_sviewer.dir/src/node.cpp.o
.PHONY : src/node.cpp.o

src/node.i: src/node.cpp.i
.PHONY : src/node.i

# target to preprocess a source file
src/node.cpp.i:
	$(MAKE) -f CMakeFiles/id_sviewer.dir/build.make CMakeFiles/id_sviewer.dir/src/node.cpp.i
.PHONY : src/node.cpp.i

src/node.s: src/node.cpp.s
.PHONY : src/node.s

# target to generate assembly for a file
src/node.cpp.s:
	$(MAKE) -f CMakeFiles/id_sviewer.dir/build.make CMakeFiles/id_sviewer.dir/src/node.cpp.s
.PHONY : src/node.cpp.s

src/render.o: src/render.cpp.o
.PHONY : src/render.o

# target to build an object file
src/render.cpp.o:
	$(MAKE) -f CMakeFiles/id_sviewer.dir/build.make CMakeFiles/id_sviewer.dir/src/render.cpp.o
.PHONY : src/render.cpp.o

src/render.i: src/render.cpp.i
.PHONY : src/render.i

# target to preprocess a source file
src/render.cpp.i:
	$(MAKE) -f CMakeFiles/id_sviewer.dir/build.make CMakeFiles/id_sviewer.dir/src/render.cpp.i
.PHONY : src/render.cpp.i

src/render.s: src/render.cpp.s
.PHONY : src/render.s

# target to generate assembly for a file
src/render.cpp.s:
	$(MAKE) -f CMakeFiles/id_sviewer.dir/build.make CMakeFiles/id_sviewer.dir/src/render.cpp.s
.PHONY : src/render.cpp.s

src/window.o: src/window.cpp.o
.PHONY : src/window.o

# target to build an object file
src/window.cpp.o:
	$(MAKE) -f CMakeFiles/id_sviewer.dir/build.make CMakeFiles/id_sviewer.dir/src/window.cpp.o
.PHONY : src/window.cpp.o

src/window.i: src/window.cpp.i
.PHONY : src/window.i

# target to preprocess a source file
src/window.cpp.i:
	$(MAKE) -f CMakeFiles/id_sviewer.dir/build.make CMakeFiles/id_sviewer.dir/src/window.cpp.i
.PHONY : src/window.cpp.i

src/window.s: src/window.cpp.s
.PHONY : src/window.s

# target to generate assembly for a file
src/window.cpp.s:
	$(MAKE) -f CMakeFiles/id_sviewer.dir/build.make CMakeFiles/id_sviewer.dir/src/window.cpp.s
.PHONY : src/window.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... debug"
	@echo "... distclean"
	@echo "... edit_cache"
	@echo "... id_sviewer"
	@echo "... rebuild"
	@echo "... rebuild_cache"
	@echo "... release"
	@echo "... src/FBXloader.o"
	@echo "... src/FBXloader.i"
	@echo "... src/FBXloader.s"
	@echo "... src/func_event.o"
	@echo "... src/func_event.i"
	@echo "... src/func_event.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/matrix.o"
	@echo "... src/matrix.i"
	@echo "... src/matrix.s"
	@echo "... src/mesh.o"
	@echo "... src/mesh.i"
	@echo "... src/mesh.s"
	@echo "... src/node.o"
	@echo "... src/node.i"
	@echo "... src/node.s"
	@echo "... src/render.o"
	@echo "... src/render.i"
	@echo "... src/render.s"
	@echo "... src/window.o"
	@echo "... src/window.i"
	@echo "... src/window.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

